const ERROR_CODE_INVALID_INPUT = 400;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_SERVER_ERROR = 500;
const ERROR_MESSAGE_SERVER_ERROR = 'Server error';

module.exports = {
  ERROR_CODE_INVALID_INPUT,
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_SERVER_ERROR,
  ERROR_MESSAGE_SERVER_ERROR,
};
